---
title: "Lab 03a: Animal Word Cleaning"
subtitle: "CS631"
author: "Alison Hill"
output:
  html_document:
    theme: flatly
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warning = FALSE, errors = FALSE, message = FALSE, tidy = FALSE, cache = FALSE)
```

# Data
http://langcog.github.io/wordbankr/

# Packages

```{r}
library(tidyverse)
library(wordbankr)
library(here)
```

```{r}
my_animals <- c("cat", "kitty", "chicken (animal)", 
                "hen", "dog", "puppy")

# first get the items in the animal category
animal_words <- get_item_data(language = "English (American)", 
                         form = "WS") %>%
  filter(definition %in% my_animals) 

# then get instrument data for those items
animal_word_data <- get_instrument_data(
  language = "English (American)",
  form = "WS",
  items = animal_words$item_id,
  administrations = TRUE,
  iteminfo = TRUE
  ) %>% 
  mutate(produces = value == "produces") %>% 
  mutate(animal_word = case_when(
           definition %in% c("cat", "kitty") ~ "cat",
           definition %in% c("chicken (animal)", "hen") ~ "chicken",
           definition %in% c("dog", "puppy") ~ "dog"
         )) %>% 
  drop_na(animal_word)

# how many kids produce either of each word category?
animal_produced <- animal_word_data %>% 
  group_by(age, data_id, animal_word) %>% 
  summarize(produce_either = case_when(
    sum(produces, na.rm = TRUE) > 0 ~ 1,
    sum(produces, na.rm = TRUE) == 0 ~ 0
  )) %>% 
  ungroup()

# what proportion of kids at each age produce each word?
animal_age_summary <- animal_produced %>% 
  group_by(age, animal_word) %>%
  summarise(kids_produced_either = sum(produce_either, na.rm = TRUE),
            kids_responded = n_distinct(data_id),
            prop_produced = kids_produced_either / kids_responded)
```


Now let's export both data frames for the lab.

```{r}
write_csv(animal_word_data, here::here("data",
                                       "animal_word_data.csv"))
write_csv(animal_age_summary, here::here("data",
                                         "animal_age_summary.csv"))
```

